### ISSUE TITLE
Let users supply youtube-dl options

### ISSUE THREAD

**Issue by akshat1** [akshat1/video-hoarder#10]
Refer #9. We should allow users to supply their own youtube-dl options, using which they may be able to control naming conventions and download quality etc.

**Comment by akshat1** [comment]
See https://github.com/ytdl-org/youtube-dl/blob/master/README.md#configuration

**Comment by Ultrawipf** [comment]
Even better than only the config file would be the option to override settings with checkboxes or drop downs in the "add to queue" window.
So you could have a default config with "embed subtitles and write description" but could also add an item where you don't want subtitles embedded.

**Comment by akshat1** [comment]
@Ultrawipf yes that would be a good thing to have. I'll add it as a new feature request item, but it'll be a while before I get to it.

As an aside, did you discover this repo through r/data-hoarder? I'm trying to figure out a good way to announce updates and I wonder what is a good way to do that.

**Comment by Ultrawipf** [comment]
Yes i found it there and left you a comment some time ago but only now got to install it on my server and really test it. Much nicer than my previous solution apart from a few usability things that you already have planned (clear list, setting options in ui and so on). 

Another feature idea:
Persistent monitored playlist. Queues a link periodically until manual removal. This would work nicely with the archive-file option.

And i see that it generates >1.5MB of log spam per download in the docker log... Would be nice if it didn't log every status message.

Also it seems like it does not honor my config file? Added as a mount to /app/youtube-dl.conf. But i will have to check this with the newer release again. 

Where to post updates? Not sure. Maybe advertise it there again once the usability is improved. I would definetly support this project and continue to use it once its fit for daily use.

**Comment by akshat1** [comment]
I'm glad you found it useful :)

I have logged
- a feature request #27 for letting the user override settings for each download.
- a bug for controlling log spam.

The feature to specify your own config file is not in the `:latest` tag yet (it's available in the rc tag release-0.0.5-rc4). I'm hoping to push out a new version of the stable branch this weekend, after which it should be available in `:latest`.

Thanks for your support. Please feel free to log feature-requests and bugs yourself.
